export const GROUPS_REQUEST = "GROUPS_REQUEST";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";
export const GROUPS_FAILED = "GROUPS_FAILED";

export const GROUPS__ACTIVE_REQUEST = "GROUPS__ACTIVE_REQUEST";
export const GROUPS__ACTIVE_SUCCESS = "GROUPS__ACTIVE_SUCCESS";
export const GROUPS__ACTIVE_FAILED = "GROUPS__ACTIVE_FAILED";

export const GROUPS__ALL_REQUEST = "GROUPS__ALL_REQUEST";
export const GROUPS__ALL_SUCCESS = "GROUPS__ALL_SUCCESS";
export const GROUPS__ALL_FAILED = "GROUPS__ALL_FAILED";

export const GROUPS__ARCHIVE_REQUEST = "GROUPS__ARCHIVE_REQUEST";
export const GROUPS__ARCHIVE_SUCCESS = "GROUPS__ARCHIVE_SUCCESS";
export const GROUPS__ARCHIVE_FAILED = "GROUPS__ARCHIVE_FAILED";

export const GROUPS__FAVORITE_ADD_REQUEST = "GROUPS__FAVORITE_ADD_REQUEST";
export const GROUPS__FAVORITE_ADD_SUCCESS = "GROUPS__FAVORITE_ADD_SUCCESS";
export const GROUPS__FAVORITE_ADD_FAILED = "GROUPS__FAVORITE_ADD_FAILED";

export const GROUPS__FAVORITE_REMOVE_REQUEST =
  "GROUPS__FAVORITE_REMOVE_REQUEST";
export const GROUPS__FAVORITE_REMOVE_SUCCESS =
  "GROUPS__FAVORITE_REMOVE_SUCCESS";
export const GROUPS__FAVORITE_REMOVE_FAILED = "GROUPS__FAVORITE_REMOVE_FAILED";

export const GROUPS__ARCHIVE_ADD_REQUEST = "GROUPS__FAVORITE_ADD_REQUEST";
export const GROUPS__ARCHIVE_ADD_SUCCESS = "GROUPS__FAVORITE_ADD_SUCCESS";
export const GROUPS__ARCHIVE_ADD_FAILED = "GROUPS__FAVORITE_ADD_FAILED";

export const GROUPS__ARCHIVE_REMOVE_REQUEST =
  "GROUPS__ARCHIVE_REMOVE_REQUEST";
export const GROUPS__ARCHIVE_REMOVE_SUCCESS =
  "GROUPS__ARCHIVE_REMOVE_REQUEST_SUCCESS";
export const GROUPS__ARCHIVE_REMOVE_FAILED = "GROUPS__ARCHIVE_REMOVE_REQUEST_FAILED";
