export const GROUPS_REQUEST = "GROUPS_REQUEST";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";
export const GROUPS_FAILED = "GROUPS_FAILED";

export const GROUPS__ACTIVE_REQUEST = "GROUPS__ACTIVE_REQUEST";
export const GROUPS__ACTIVE_SUCCESS = "GROUPS__ACTIVE_SUCCESS";
export const GROUPS__ACTIVE_FAILED = "GROUPS__ACTIVE_FAILED";
