export const GROUP_MODAL_OPEN = "GROUP_MODAL_OPEN";
export const GROUP_MODAL_CLOSE = "GROUP_MODAL_CLOSE";
export const STUDENT_MODAL_OPEN = "STUDENT_MODAL_OPEN";
export const STUDENT_MODAL_CLOSE = "STUDENT_MODAL_CLOSE";