export const STUDENTS_REQUEST = "STUDENTS_REQUEST";
export const STUDENTS_SUCCESS = "STUDENTS_SUCCESS";
export const STUDENTS_FAILED = "STUDENTS_FAILED";

export const STUDENTS__ALL_REQUEST = "STUDENTS__ALL_REQUEST";
export const STUDENTS__ALL_SUCCESS = "STUDENTS__ALL_SUCCESS";
export const STUDENTS__ALL_FAILED = "STUDENTS__ALL_FAILED";
